language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
            - cmake-data
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: linux
      dist: trusty
      env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - cmake
            - cmake-data
          sources: *sources
            - george-edison55-precise-backports
    - os: osx
      osx_image: xcode7
      before_install:
        - brew update
        - brew install cmake
    - os: osx
      osx_image: xcode8
before_script:
  - cmake --version
  - cmake .
script:
  - CXX --version
  - make
  - ctest -V . 
