language: generic

sudo: required
dist: precise

matrix:
  include:
    - os: linux
      env: CXX="g++-5" CC="gcc-5"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-5
            - g++-5
            - cmake
            - cmake-data
          sources: &sources
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: linux
      env: CXX="g++-6" CC="gcc-6"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
            - cmake
            - cmake-data
          sources: *sources
    - os: linux
      env: CXX="clang++-3.7" CC="clang-3.7"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.7
            - g++-5
            - cmake
            - cmake-data
          sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: linux
      env: CXX="clang++-3.8" CC="clang-3.8"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - g++-5
            - cmake
            - cmake-data
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: osx
      osx_image: xcode7
      before_install:
        - brew update
        - brew install cmake
    - os: osx
      osx_image: xcode8
before_script:
  - cmake --version
  - cmake .
script:
  - make
  - ctest -V .
