language: generic
dist: trusty
matrix:
  include:
    - os: linux
      env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
            - cmake-data
          sources: &sources
            - llvm-toolchain-trusty-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: linux
      env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
            - cmake
            - cmake-data
          sources: *sources
    - os: linux
      env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - g++-5
            - cmake
            - cmake-data
          sources: *sources
    - os: linux
      env: CXX=clang++-3.9 CC=clang-3.9
      addons:
        apt:
          packages:
            - clang-3.9
            - g++-5
            - cmake
            - cmake-data
          sources: *sources
    - os: osx
      osx_image: xcode7
      before_install:
        - brew update
        - brew install cmake
    - os: osx
      osx_image: xcode8
before_script:
  - cmake --version
  - cmake .
script:
  - make
  - ctest -V .
