language: generic

sudo: false
dist: trusty

matrix:
  include:
    - os: linux
      env: CXX="g++-4.9" CC="gcc-4.9"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-4.9
            - g++-4.9
            - cmake
            - cmake-data
          sources: &sources
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: linux
      env: CXX="g++-5" CC="gcc-5"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-5
            - g++-5
            - cmake
            - cmake-data
          sources: *sources
    - os: linux
      env: CXX="g++-6" CC="gcc-6"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
            - cmake
            - cmake-data
          sources: *sources
    - os: linux
      env: CXX="g++-7" CC="gcc-7"
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-7
            - g++-7
            - cmake
            - cmake-data
          sources: *sources
    - os: linux
      env: CXX="clang++-3.6" CC="clang-3.6"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.6
            - g++-5
            - cmake
            - cmake-data
          sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: linux
      env: CXX="clang++-3.7" CC="clang-3.7"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.7
            - g++-5
            - cmake
            - cmake-data
          sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: linux
      env: CXX="clang++-3.8" CC="clang-3.8"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
            - g++-5
            - cmake
            - cmake-data
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: linux
      env: CXX="clang++-3.9" CC="clang-3.9"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.9
            - g++-5
            - cmake
            - cmake-data
          sources:
            - llvm-toolchain-trusty-3.9
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: linux
      env: CXX="clang++-4.0" CC="clang-4.0"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-4.0
            - g++-5
            - cmake
            - cmake-data
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: linux
      env: CXX="clang++-5.0" CC="clang-5.0"
      compiler: clang
      addons:
        apt:
          packages:
            - clang-5.0
            - g++-5
            - cmake
            - cmake-data
          sources:
            - llvm-toolchain-trusty
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8
-before_script:
  - cmake --version
  - cmake .
-script:
  - make
  - ctest -V .
