image:
- Visual Studio 2015
- Visual Studio 2017

platform: Any CPU

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Debug
  - ctest .
