image:
  - Visual Studio 2017

platform:
  - x86
  - x64

environment:
  matrix:
     - GENERATOR: "Visual Studio 14 2015"
       CONFIG: Debug
     - GENERATOR: "Visual Studio 14 2015"
       CONFIG: Release
     - GENERATOR: "Visual Studio 15 2017"
       CONFIG: Debug
     - GENERATOR: "Visual Studio 15 2017"
       CONFIG: Release

build_script:
  - md build
  - cd build
  - cmake -G "$(GENERATOR)" ..
  - cmake --build . --config $(CONFIG)
  - ctest .

matrix:
  fast_finish: true
