image:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Debug
  - ctest .

environment:
  matrix:
     - GENERATOR: "Visual Studio 14"
       CONFIG: Debug
     - GENERATOR: "Visual Studio 14"
       CONFIG: Release
     - GENERATOR: "Visual Studio 15"
       CONFIG: Debug
     - GENERATOR: "Visual Studio 15"
       CONFIG: Release

matrix:
  fast_finish: true
